//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snet.CopilotProxy {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snet.CopilotProxy.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 构建失败，退出代码: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_BuildFailed {
            get {
                return ResourceManager.GetString("Error_BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 构建脚本不存在，请先配置环境 的本地化字符串。
        /// </summary>
        internal static string Error_BuildScriptNotFound {
            get {
                return ResourceManager.GetString("Error_BuildScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 检查更新失败: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_CheckUpdateFailed {
            get {
                return ResourceManager.GetString("Error_CheckUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 初始化失败: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_InitFailed {
            get {
                return ResourceManager.GetString("Error_InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 未检测到 Node.js，请前往 https://nodejs.org/zh-cn/download 下载安装后重启应用 的本地化字符串。
        /// </summary>
        internal static string Error_NodeJsNotFound {
            get {
                return ResourceManager.GetString("Error_NodeJsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 读取输出流失败: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_ReadStreamFailed {
            get {
                return ResourceManager.GetString("Error_ReadStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 删除 .dist 失败: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_ReBuildDeleteFailed {
            get {
                return ResourceManager.GetString("Error_ReBuildDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 脚本文件不存在: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_ScriptNotFound {
            get {
                return ResourceManager.GetString("Error_ScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 启动脚本不存在，请先构建 的本地化字符串。
        /// </summary>
        internal static string Error_StartScriptNotFound {
            get {
                return ResourceManager.GetString("Error_StartScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 停止失败: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_StopFailed {
            get {
                return ResourceManager.GetString("Error_StopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 停止失败，请手动关闭 的本地化字符串。
        /// </summary>
        internal static string Error_StopFailedManual {
            get {
                return ResourceManager.GetString("Error_StopFailedManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 关闭代理服务失败: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_StopServiceFailed {
            get {
                return ResourceManager.GetString("Error_StopServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Error ] 启动时清理残留服务失败: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_StopStaleServiceFailed {
            get {
                return ResourceManager.GetString("Error_StopStaleServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局异常捕获 的本地化字符串。
        /// </summary>
        internal static string GlobalException {
            get {
                return ResourceManager.GetString("GlobalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 构建完成 的本地化字符串。
        /// </summary>
        internal static string Info_BuildCompleted {
            get {
                return ResourceManager.GetString("Info_BuildCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 开始构建… 的本地化字符串。
        /// </summary>
        internal static string Info_BuildStarting {
            get {
                return ResourceManager.GetString("Info_BuildStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 正在检查更新… 的本地化字符串。
        /// </summary>
        internal static string Info_CheckingUpdate {
            get {
                return ResourceManager.GetString("Info_CheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 配置已保存 的本地化字符串。
        /// </summary>
        internal static string Info_ConfigSaved {
            get {
                return ResourceManager.GetString("Info_ConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 配置已保存，正在重启服务以应用新配置… 的本地化字符串。
        /// </summary>
        internal static string Info_ConfigSavedRestarting {
            get {
                return ResourceManager.GetString("Info_ConfigSavedRestarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 配置已同步到 .dist 的本地化字符串。
        /// </summary>
        internal static string Info_ConfigSynced {
            get {
                return ResourceManager.GetString("Info_ConfigSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 配置未变更，跳过保存 的本地化字符串。
        /// </summary>
        internal static string Info_ConfigUnchanged {
            get {
                return ResourceManager.GetString("Info_ConfigUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] .dist 中无配置文件，正在创建默认配置… 的本地化字符串。
        /// </summary>
        internal static string Info_DistNoConfig {
            get {
                return ResourceManager.GetString("Info_DistNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 发现新版本！当前: {0}，最新: {1}，请前往 https://github.com/shunnet/CopilotProxy/releases 下载 的本地化字符串。
        /// </summary>
        internal static string Info_NewVersion {
            get {
                return ResourceManager.GetString("Info_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] Node.js {0} 的本地化字符串。
        /// </summary>
        internal static string Info_NodeJs {
            get {
                return ResourceManager.GetString("Info_NodeJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 服务进程已终止 的本地化字符串。
        /// </summary>
        internal static string Info_ProcessTerminated {
            get {
                return ResourceManager.GetString("Info_ProcessTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 已删除 .dist 构建目录 的本地化字符串。
        /// </summary>
        internal static string Info_ReBuildDeleted {
            get {
                return ResourceManager.GetString("Info_ReBuildDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 正在停止服务… 的本地化字符串。
        /// </summary>
        internal static string Info_ReBuildStopping {
            get {
                return ResourceManager.GetString("Info_ReBuildStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 正在重启服务… 的本地化字符串。
        /// </summary>
        internal static string Info_ServiceRestarting {
            get {
                return ResourceManager.GetString("Info_ServiceRestarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 正在启动服务… 的本地化字符串。
        /// </summary>
        internal static string Info_ServiceStarting {
            get {
                return ResourceManager.GetString("Info_ServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 服务已停止 的本地化字符串。
        /// </summary>
        internal static string Info_ServiceStopped {
            get {
                return ResourceManager.GetString("Info_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 正在停止服务… 的本地化字符串。
        /// </summary>
        internal static string Info_ServiceStopping {
            get {
                return ResourceManager.GetString("Info_ServiceStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Info ] 已是最新版本（当前: {0}，最新: {1}） 的本地化字符串。
        /// </summary>
        internal static string Info_UpToDate {
            get {
                return ResourceManager.GetString("Info_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Shunnet.top ] Copilot 模型代理工具 的本地化字符串。
        /// </summary>
        internal static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知异常 的本地化字符串。
        /// </summary>
        internal static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 [ Shunnet.top ] Copilot 模型代理工具 的本地化字符串。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string 停止 {
            get {
                return ResourceManager.GetString("停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string 关闭 {
            get {
                return ResourceManager.GetString("关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string 启动 {
            get {
                return ResourceManager.GetString("启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string 操作 {
            get {
                return ResourceManager.GetString("操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持 Visual Studio2026 与 Visual Studio Code 的本地化字符串。
        /// </summary>
        internal static string 支持_Visual_Studio2026_与_Visual_Studio_Code {
            get {
                return ResourceManager.GetString("支持 Visual Studio2026 与 Visual Studio Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示窗口 的本地化字符串。
        /// </summary>
        internal static string 显示窗口 {
            get {
                return ResourceManager.GetString("显示窗口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构建 的本地化字符串。
        /// </summary>
        internal static string 构建 {
            get {
                return ResourceManager.GetString("构建", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        internal static string 检查更新 {
            get {
                return ResourceManager.GetString("检查更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string 清空 {
            get {
                return ResourceManager.GetString("清空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string 设置 {
            get {
                return ResourceManager.GetString("设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        internal static string 重启 {
            get {
                return ResourceManager.GetString("重启", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建 的本地化字符串。
        /// </summary>
        internal static string 重建 {
            get {
                return ResourceManager.GetString("重建", resourceCulture);
            }
        }
    }
}
